#!/bin/bash
MAC="$1"
IP="$2"

if [ "${MAC^^}" = "50:EB:F6:57:41:CF" ]; then
cat > wakemaboi <<EOM
#!/bin/bash

echo -n "Warming up transistors"
sleep 1; echo -n "."; sleep 1; echo -n "."; sleep 1; echo "."; sleep 1;
echo -n "Assembling magic packet"
sleep 1; echo -n "."; sleep 1; echo -n "."; sleep 1; echo "."; sleep 1;
echo -n "Preparing magic packet for launch"
sleep 1; echo -n "."; sleep 1; echo -n "."; sleep 1; echo "."; sleep 1;
echo -n "Preheating IPv4 engines"
sleep 1; echo -n "."; sleep 1; echo -n "."; sleep 1; echo "."; sleep 1;
echo "All systems ready."
sleep 2;
echo "Launching magic packet."
for i in \$(seq 1 100); do
  for j in \$(seq 1 \$i); do
    echo -n " "
  done
  sleep 0.05
  echo -n -e " 🔥====>\r"
done
sleep 2;
echo "UDP angel spreading its wings!"
sleep 4;
echo "I repeat, UDP angel spreading its wings!"
sleep 4;
echo "It's a small step for a Hansel but a big energy saving for mankind."
sleep 4;

./easywake ${MAC} ${IP}
EOM
else
cat > wakemaboi <<EOM
#!/bin/bash  
echo "Waking ya boi up..."
./easywake ${MAC} ${IP}
EOM
fi

chmod a+x wakemaboi 
